---
version: '3'

networks:
  redis:
    name: redis

services:

  podinfo:
    image: node18:redis
    networks:
      - redis

  redis:
    image: redis:alpine3.17
    networks:
      redis:
        aliases:
          - redis
