---
version: '3.8'

networks:
  redis:
    name: redis

services:

  podinfo:
    image: node18:redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine3.17
    networks:
      redis:
        aliases:
          - redis
