---
name: Build
on:
  workflow_call:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: "."
          load: true
          push: false
          tags: abienkow/redisapp
          cache-to: type=gha
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/redisapp.tar

      - name: debug
        run: |
          docker images

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: abienkow-redisapp
          path: /tmp/redisapp.tar
