---
name: Build and Test
on:
  pull_request:
    type: [opened,reopened,synchronized]
  push:
    branches:
      - main
    tags:
      - v\d+\.\d+\.\d+

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
#- name: install node dependencies
#        working-directory: "${{ github.workspace }}/app"
#        run: |
#          npm ci

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          workdir: 'app/'

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: "."
          push: false
          tags: abienkow/node-redis
          cache-to: type=gha
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/node-redis.tar

      - name: debug
        run: |
          docker images

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-redis
          path: /tmp/node-redis.tar
