---
name: Build and Test
on:
  workflow_call:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          workdir: 'app/'

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install packages
        run: |
          cd app
          npm ci

      - name: run tests
        run: |
          cd app 
          ./node_modules/.bin/jest

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: "."
          load: true
          push: false
          tags: abienkow/redisapp
          cache-to: type=gha
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/redisapp.tar

      - name: debug
        run: |
          docker images

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: abienkow-redisapp
          path: /tmp/redisapp.tar
