---
name: CI Pipeline
on:
  pull_request:
    type: [opened,reopened,synchronized]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  lint:
    uses: "./.github/workflows/lint.yml"

  test:
    uses: "./.github/workflows/test.yml"

  build:
    uses: "./.github/workflows/build.yml"
