---
name: Build and Test
on:
  pull_request:
    types: [opened,reopened,synchronized]
  push:
    branches:
      - main
    tags:
      - v\d+\.\d+\.\d+

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: "."
          push: false
          tags: abienkow/node-redis
          cache-to: type=gha
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/node-redis.tar

      - name: debug
        run: |
          docker images

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-redis
          path: /tmp/node-redis.tar
