---
name: Test
on:
  workflow_call:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install packages
        run: |
          cd app
          npm ci

      - name: run tests
        run: |
          cd app 
          ./node_modules/.bin/jest
